feat: add localization for appBar title and body text
RED-offline/employee_app2 pull request #2
Opened 2023-03-16 08:31 UTC by RED-offline

add localization
hope everything is ok :)

2023-03-16 10:13 UTC, RusKryzhanovskiy requested changes
Форматуй код перед пушем

2023-03-16 10:13 UTC, RusKryzhanovskiy commented on lib/app/view/app.dart
> +      locale: Locale('uk'),
Ти таким чином хардкодиш локаль. Не треба. Хай бере з системи

2023-03-16 10:13 UTC, RusKryzhanovskiy commented on lib/l10n/arb/app_uk.arb
> +
Так багато не треба ентерів

2023-03-16 10:13 UTC, RusKryzhanovskiy commented on lib/l10n/arb/app_uk.arb
> +
Тут

2023-03-16 10:13 UTC, RusKryzhanovskiy commented on lib/l10n/arb/app_en.arb
>  }
А тут не додав ентер в кінці файлу

2023-03-16 10:13 UTC, RusKryzhanovskiy commented on lib/l10n/arb/app_en.arb
> +
Багато ентерів

2023-03-17 07:17 UTC, RED-offline commented on lib/app/view/app.dart
> +      locale: Locale('uk'),
та то я дурник тестив, міняв локалі, і забув видалить, все виправлю

2023-03-17 09:19 UTC, merged